# training configuration
epochs: 200  # number of epochs to train the model
batch_size: 8  # batch size for the dataloader
learning_rate: 0.0001  # learning rate for the optimizer

# model configuration
anchors: 64  # number of horizontal anchors in the input image
classes: 128  # number of classes (grid cells) for each anchor, background not included
pool_channels: 8  # number of output channels of the pooling layer
fc_hidden_size: 2048  # number of units in the hidden layer of the fully connected part