# training configuration
epochs: 250  # number of epochs to train the model
batch_size: 32  # batch size for the dataloader
learning_rate: 0.001  # learning rate for the optimizer
weight_decay: 0.001
gradient_clip: 1.0
warmup_pct: 0.03
final_div_factor: 10000.0
ylimit_loss_weight: 0.5  # weight coefficient for the loss function (see paper eq. 3)
perspective_weight_limit_percentile: 95  # percentile for the calculation of the perspective weight limit (Wmax in paper eq. 1.2) (null for no perspective weight limit)

# model configuration
anchors: 64  # number of horizontal anchors in the input image
pool_channels: 8  # number of output channels of the pooling layer
fc_hidden_size: 2048  # number of units in the hidden layer of the fully connected part
dinov3_intermediate_layers: 4
dinov3_layer_set: four_last
dinov3_use_cls_token: False
dinov3_adapter_channels: 256
dinov3_adapter_depth: 1
rtdetrv4_use_encoder: True
rtdetrv4_feature_level: 1
rtdetrv4_adapter_channels: 256
rtdetrv4_adapter_depth: 1
