# training configuration
epochs: 300  # number of epochs to train the model
batch_size: 8  # batch size for the dataloader
learning_rate: 0.0001  # learning rate for the optimizer

# model configuration
decoder_channels: [256, 128, 64, 32, 16]  # number of output channels of the decoder blocks
